version: '3'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000